# 필터링 규칙 설정
# 돌파 매매 전략 기반 필터링 조건들

# === 필수 조건 (Must Pass) ===
# 모든 필수 조건을 만족해야 통과
require_price_above_ma200: true      # 현재가 > 200일 이동평균선
require_price_above_high60: true     # 현재가 > 60일 고점 돌파

# === 보조 조건 (Optional) ===
# 설정된 최소 개수 이상 만족해야 통과
check_macd_positive: true            # MACD > 0 (양봉 전환 초기)
check_adx_strength: true             # ADX >= threshold (추세 강도)
check_golden_cross: true             # MA50 > MA200 (골든크로스)
check_volume_surge: true             # 거래량 > 20일 평균
check_supertrend_bullish: true       # Supertrend 상승 신호 ('bull')

# === Supertrend 설정 ===
supertrend_signal_value: 'bull'      # 'bull', 'bear', 'neutral' 중 선택

# === 임계값 설정 ===
adx_threshold: 20                    # ADX 강세 판단 기준값
min_optional_conditions_passed: 2    # 보조 조건 최소 통과 개수
max_filtered_tickers: 20             # 최대 선별 종목 수

# === 로깅 설정 ===
enable_debug_logging: false          # 디버그 로그 활성화 여부 
# ============================================================
# Breakout‑filter configuration with selectable MODE
# Set `mode:` to either `tight` or `lose`
# ============================================================

#mode: tight          # <‑‑ change to 'tight' or `lose` for relaxed filtering
mode: lose          # <‑‑ change to 'tight' or `lose` for relaxed filtering

# -----------------------------------------------------------------
# MODE DEFINITIONS
# -----------------------------------------------------------------
modes:
  tight:               # 기존 "타이트" 설정
    # ---- 필수 조건 ----
    require_price_above_ma200: true
    require_price_above_high60: true

    # ---- 보조 조건 ----
    check_macd_positive:  true
    check_adx_strength:   true
    check_golden_cross:   true
    check_volume_surge:   true

    # ---- 임계값 ----
    adx_threshold: 20
    min_optional_conditions_passed: 2
    max_filtered_tickers: 20

  lose:                # 완화(루즈) 설정
    # ---- 필수 조건 ----
    require_price_above_ma200: true          # 200MA 위 여부
    require_price_above_high60: false         # 60일 고점 돌파, 필수 아님
    #price_above_ma200_ratio: 0.85             # 200MA 의 n% 이상 허용
    price_near_high60_ratio: 0.8             # 60일 고점의 n% 이상 허용

    # ---- 보조 조건 ----
    check_macd_positive:  true
    check_adx_strength:   true
    check_golden_cross:   true               # 초기 돌파 시 골든크로스
    check_volume_surge:   true

    # ---- 임계값 ----
    adx_threshold: 14
    min_optional_conditions_passed: 2
    max_filtered_tickers: 30

# -----------------------------------------------------------------
# LOGGING (공통)
# -----------------------------------------------------------------
enable_debug_logging: true

# ============================================================
# 하이브리드 필터링 설정 (정적+동적 지표 조합)
# ============================================================

# === 하이브리드 필터링 옵션 ===
enable_hybrid_filtering: true        # 정적+동적 지표 조합 활성화

# === 추가 동적 지표 조건 ===
check_rsi_range: true                # RSI 30-70 범위 확인
check_bollinger_breakout: true       # 볼린저밴드 상단 근접
check_macd_signal_cross: true        # MACD 히스토그램 양수

# === 동적 지표 임계값 ===
rsi_min: 30                          # RSI 최소값
rsi_max: 70                          # RSI 최대값
bb_proximity_ratio: 0.95             # 볼린저 상단 근접 비율
macd_hist_min: 0                     # MACD 히스토그램 최소값

# === 데이터 소스 매핑 ===
static_indicators_source: "static_indicators"
dynamic_indicators_source: "ohlcv"

# === 하이브리드 필터링 조건 가중치 ===
static_weight: 0.6                   # 정적 지표 가중치
dynamic_weight: 0.4                  # 동적 지표 가중치

# === 하이브리드 점수 기준 ===
min_hybrid_score: 2.0                # 하이브리드 모드 최소 점수
min_static_only_score: 1.5           # 정적 전용 모드 최소 점수

# ============================================================
# 시장 체온계(Market Thermometer) 설정
# ============================================================

# === 시장 체온계 임계값 ===
market_thermometer:
  thresholds:
  # === 실제 운영용 시장 체온계 임계값 ===
    min_pct_up: 45.0                  # 최소 상승 종목 비율
    max_top10_volume: 70.0            # 최대 상위 10개 집중도  
    min_ma200_above: 25.0             # 최소 MA200 상회 비율
    min_sentiment_score: 60.0         # 최소 종합 점수
  
  # === 점수 가중치 ===
  weights:
    price_distribution: 0.4          # 등락률 분포 가중치
    volume_concentration: 0.3        # 거래대금 집중도 가중치
    ma200_ratio: 0.3                 # MA200 상회 비율 가중치
  
  # === 로깅 설정 ===
  logging:
    enable_detailed_logs: true       # 상세 로그 활성화
    save_sentiment_history: true     # 시장 분위기 히스토리 저장
  
  # === 시장 상황별 점수 기준 ===
  score_thresholds:
    bullish: 75                      # 강세장 기준 점수
    neutral: 60                      # 중립장 기준 점수
    bearish: 45                      # 약세장 기준 점수

