# config/strategy.yaml - 통합된 전략 및 트레이딩 설정 (테스트 모드)

# 기본 전략 설정
atr:
  period: 14           # ATR 계산 기간

risk:
  pct: 0.02            # 포지션당 허용 리스크 비율 (테스트용 증가)

pyramiding:
  max_add_ons: 3       # 최대 추가 매수 횟수
  add_on_ratio: 0.5    # 초기 비중 대비 추가 매수 비율

trailing_stop:
  atr_multiplier: 1.5  # ATR에 곱할 배수 (트레일링 스톱) - 테스트용 증가

# GPT 분석 설정
gpt_analysis:
  score_threshold: 70                # GPT 분석 점수 임계값 (테스트용 낮춤)
  confidence_threshold: 0.7          # 신뢰도 임계값 (테스트용 낮춤)
  batch_size: 3                      # 배치 처리 크기 (테스트용 감소)
  memory_threshold_mb: 300           # 메모리 임계값 (MB) (테스트용 감소)
  max_tokens: 2000                   # 최대 토큰 수 (테스트용 감소)
  temperature: 0.3                   # GPT 온도 설정
  retry_attempts: 2                  # 재시도 횟수 (테스트용 감소)
  timeout_seconds: 20                # 타임아웃 (초) (테스트용 감소)
  analysis_period_days: 100          # 분석 기간 (테스트용 감소)

# 리스크 관리 설정 (테스트용 조정)
risk_management:
  base_stop_loss: 2.0                # 기본 손절율 (%) (테스트용 감소)
  base_take_profit: 4.0              # 기본 익절율 (%) (테스트용 감소)
  max_volatility_multiplier: 2.0     # 최대 변동성 배수 (테스트용 감소)
  max_position_size: 0.03            # 최대 포지션 크기 (3%) (테스트용 감소)
  base_position_size: 0.01           # 기본 포지션 크기 (1%) (테스트용 감소)
  kelly_fraction: 0.5                # Kelly fraction (테스트용 증가)
  max_daily_trades: 5                # 일일 최대 거래 수 (테스트용 감소)
  max_portfolio_risk: 0.1            # 최대 포트폴리오 리스크 (10%) (테스트용 감소)

# 필터링 설정 (테스트용 조정)
filtering:
  max_filtered_tickers: 10           # 최대 필터링 티커 수 (테스트용 감소)
  min_market_cap: 50000000           # 최소 시가총액 (5천만) (테스트용 감소)
  min_volume_24h: 500000            # 최소 24시간 거래량 (50만) (테스트용 감소)
  price_change_threshold: 3.0        # 가격 변동 임계값 (%) (테스트용 감소)
  rsi_oversold: 25                   # RSI 과매도 구간 (테스트용 조정)
  rsi_overbought: 75                 # RSI 과매수 구간 (테스트용 조정)
  enable_volume_filter: true         # 거래량 필터 활성화
  enable_volatility_filter: true     # 변동성 필터 활성화

# 백테스트 설정 (테스트용 조정)
backtest:
  default_period_days: 14            # 기본 백테스트 기간 (일) (테스트용 감소)
  initial_capital: 1000000           # 초기 자본금 (100만원) (테스트용 감소)
  commission_rate: 0.0005            # 수수료율 (0.05%)
  slippage_rate: 0.001               # 슬리피지율 (0.1%)
  enable_auto_report: true           # 자동 리포트 생성
  report_frequency: "daily"          # 리포트 주기 (daily/weekly/monthly)

# 성능 모니터링 설정
performance:
  monitoring_enabled: true           # 성능 모니터링 활성화
  metrics_retention_days: 30         # 메트릭 보관 기간 (일) (테스트용 감소)
  alert_win_rate_threshold: 0.3      # 승률 경고 임계값 (테스트용 낮춤)
  alert_drawdown_threshold: 0.1      # 최대 손실 경고 임계값 (10%) (테스트용 감소)
  performance_review_interval: 3     # 성능 검토 주기 (일) (테스트용 감소)

# 실시간 적응 설정 (테스트용 조정)
adaptive_strategy:
  enable_auto_adjustment: false      # 자동 파라미터 조정 비활성화 (테스트용)
  adjustment_frequency: 7            # 조정 주기 (일)
  min_trades_for_adjustment: 10      # 조정을 위한 최소 거래 수 (테스트용 감소)
  performance_window_days: 7         # 성과 평가 윈도우 (일) (테스트용 감소)
  adjustment_sensitivity: 0.2        # 조정 민감도 (0.2 = 20%) (테스트용 증가)

# VCP 패턴 분석 설정 (테스트용 조정)
vcp_settings:
  min_base_weeks: 5                    # 최소 베이스 기간 (주) (테스트용 감소)
  max_base_weeks: 30                   # 최대 베이스 기간 (주) (테스트용 감소)
  volume_decline_threshold: 0.4        # 거래량 감소 임계값 (40%) (테스트용 증가)
  breakout_volume_multiplier: 1.3      # 브레이크아웃 시 거래량 배수 (테스트용 감소)
  min_contractions: 1                  # 최소 수축 횟수 (테스트용 감소)
  vcp_score_threshold: 50              # VCP 패턴 인정 점수 임계값 (테스트용 낮춤)
  volatility_decrease_threshold: 0.7   # 변동성 감소 임계값 (테스트용 감소)

# Weinstein 4단계 분석 설정 (테스트용 조정)
stage_settings:
  stage2_entry_weight: 1.0             # Stage2 진입 가중치
  stage1_transition_weight: 0.7        # Stage1 전환 가중치 (테스트용 감소)
  stage3_exit_weight: 0.2              # Stage3 퇴장 가중치 (테스트용 감소)
  stage4_avoid_weight: 0.1             # Stage4 회피 가중치
  ma50_period: 50                      # MA50 기간
  ma200_period: 200                    # MA200 기간
  slope_calculation_days: 10           # 기울기 계산 기간 (테스트용 감소)
  stage_confidence_threshold: 0.5      # 단계 신뢰도 임계값 (테스트용 낮춤)

# 브레이크아웃 진입 조건 설정 (테스트용 조정)
breakout_settings:
  strong_buy_vcp_score: 60             # 강력 매수 VCP 점수 (테스트용 낮춤)
  strong_buy_stage_confidence: 0.6     # 강력 매수 Stage 신뢰도 (테스트용 낮춤)
  weak_buy_vcp_score: 40               # 약한 매수 VCP 점수 (테스트용 낮춤)
  weak_buy_stage_confidence: 0.4       # 약한 매수 Stage 신뢰도 (테스트용 낮춤)
  sell_stage_confidence: 0.5           # 매도 Stage 신뢰도 (테스트용 낮춤)
  max_position_size: 0.03              # 최대 포지션 크기 (3%) (테스트용 감소)
  base_position_size: 0.01             # 기본 포지션 크기 (1%) (테스트용 감소)
  stop_loss_buffer: 0.015              # 손절 버퍼 (1.5%) (테스트용 감소)
  target_multiplier: 1.1               # 목표가 배수 (테스트용 감소)

# 전략 통합 가중치 (테스트용 조정)
strategy_weights:
  vcp_weight: 0.3                      # VCP 분석 가중치 (테스트용 감소)
  stage_weight: 0.3                    # Stage 분석 가중치
  technical_weight: 0.3                # 기존 기술적 분석 가중치 (테스트용 증가)
  gpt_weight: 0.1                      # GPT 분석 가중치